version: '3.8'

services:
  docker-backup:
    # build:
    #   context: .
    #   dockerfile: dockerfile
    container_name: docker-backup
    image: ghcr.io/jdrozdnovak/docker-backup:latest
    environment:
      - CRON_SCHEDULE="0 */6 * * *"
      - RCLONE_REMOTE_NAME
      - RCLONE_REMOTE_FOLDER
      - RCLONE_REMOTE_PASSWORD=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf
      - /docker/:/docker/
