name: Docker Backup Image Creation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the docker_backup docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jdrozdnovak/docker-backup:$GITHUB_RUN_NUMBER
            ghcr.io/jdrozdnovak/docker-backup:latest
        env:
          GITHUB_REF: ${{ vars.GITHUB_RUN_NUMBER }}